version: 2
updates:
- package-ecosystem: npm
  directory: "/streamlit-component-lib-react-hooks"
  schedule:
    interval: daily

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: "daily"
