version: "2.1"

services:
  backend:
    build: ./template
    volumes:
      - ./template:/srv/app
    ports:
      - "3000:3000"
      - "8501:8501"
  frontend:
    build: ./template/st_clickable_text/frontend/
    image: node:12
    ports:
      - "3001:3001"
    volumes:
      - ./template/st_clickable_text/frontend/src:/srv/app/src
      - ./template/st_clickable_text/frontend/build:/srv/app/build
    stdin_open: true